platform :ios, '9.0'
use_frameworks!

target 'Flatmate' do
	pod 'FacebookCore'	 
	pod 'FacebookLogin'
	pod 'MDCSwipeToChoose'
	pod 'SteviaLayout', :git => 'https://github.com/freshOS/Stevia', :branch => 'swift4'
	pod 'Koloda', :git => 'https://github.com/Yalantis/Koloda', :tag => '4.3'
	pod 'Moya'
	pod 'TPKeyboardAvoiding'
	pod 'SwiftyJSON'
end